### ISSUE TITLE
Do competitors have feedbacks to show our results in the test?

### ISSUE THREAD

**Issue by zhangrzpanda** [xmrec/xmrec.github.io#1]
I only see the deadline for results submission on January 17, 2022. Do competitors have feedbacks to show our results in the test? like real-time ranking

**Comment by aliannejadi** [comment]
Yes. We will make the leaderboard live this week. So, participants can submit their results and get a live result in the leaderboard.

**Comment by aliannejadi** [comment]
Hi, our Codalab leaderboard is now live. Please check the webiste.
