### ISSUE TITLE
the dataset can't obtain

### ISSUE THREAD

**Issue by Ljwccc** [xmrec/xmrec.github.io#2]
i get the result "The requested URL "/downloads/XMarket/DATA/us/Industrial_and_Scientific/ratings_us_Industrial_and_Scientific.txt" was not found on this server"

**Comment by hamedrab** [comment]
Thanks, for opening this issue. We will be putting in all the data soon... please check back in a few days and let us know if you still don't have access.

**Comment by Ljwccc** [comment]
Thank you for sharing the dataset, i can download it from the page!  And i want to know how can i obtain the source code for this great work,thank you!

**Comment by hamedrab** [comment]
Thanks for your interest. The code will be ready in a few days as well...
