### ISSUE TITLE
Question about XMRec data

### ISSUE THREAD

**Issue by jinweiluo** [xmrec/xmrec.github.io#3]
Hi, thanks for the collection of such a great dataset.
I have a little question about this data and I would be grateful if you can help me. 
From the CIKM paper of XMRec I can see that the #items and #unique items are not the same. (Table 1: General statistics of XMarket)
And I can not understand this sentence:  We crawled data for ∼300K unique items across all markets, which resulted in ∼4M cross-market items.
What does that mean?
The data description said that the item id is the ASIN of the product and should be unique, so why the #items not equal to #unique items.

**Comment by hamedrab** [comment]
Hi, thanks for your question. The item ids (ASINs) are the same across different markets however might come with different descriptions, language, etc depending on the target market. Our dataset provides around 300K items across 18 markets and some of those items are not available in every market, which totally makes 4M items (if an ASIN is available in all 18 markets, here we count it 18 times).

**Comment by jinweiluo** [comment]
I see.
Thanks for your great answer.
